version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
    volumes:
      - D:\dbsIrados:/var/lib/postgresql/data
    restart: always
